ALTER TABLE offers DROP CONSTRAINT offers_category_supported;
ALTER TABLE offers ADD CONSTRAINT offers_category_supported CHECK (category IN (
  'GENERAL_RETAIL', 'MOBILE_AND_TABLETS', 'COMPUTERS_AND_ACCESSORIES',
  'CONSUMER_ELECTRONICS', 'HOME_APPLIANCES', 'HOME_AND_FURNITURE',
  'FASHION_AND_LIFESTYLE', 'AUTOMOTIVE', 'TRAVEL', 'FOOD_AND_DELIVERY',
  'PAYMENTS_AND_FINANCE', 'OTHER'
));
